export let baseURL = "https://node.masplatform.net";
export let socketURL = "wss://node.masplatform.net";

if (!process.env.NODE_ENV || process.env.NODE_ENV === 'development') {
 baseURL = "http://localhost:1865";
 socketURL = "ws://localhost:1865";
}
const url = `${baseURL}/api/v1`;
const Apiconfigs = {
  connectWallet: `${url}/user/connectWallet`,
  updateprofile: `${url}/user/updateProfile`,
  donationTransactionlist: `${url}/user/donationTransactionlist`,
  sendOtp: `${url}/user/send-otp`,
  verifyOtp: `${url}/user/verify-otp`,
  profile: `${url}/user/profile`,
  myfeed: `${url}/user/myFeed`,
  myauction: `${url}/nft/listNFT`,
  mynft: `${url}/nft/nft/`,
  bundleList: `${url}/nft/bundleList`,
  nftall: `${url}/nft/allNftList`,
  likeDislikeFeed: `${url}/user/likeDislikeFeed/`,
  unSubscription: `${url}/user/unSubscription?_id=`,
  transactionList: `${url}/user/transactionList/`,
  listBanner: `${url}/admin/listBanner`,

  mysubscription: `${url}/user/mySubscriptions`,
  delnft: `${url}/nft/nft/`,
  listorder: `${url}/order/listOrder`,
  ipfsupload: `${url}/nft/ipfsUpload`,
  subscribeNow: `${url}/user/subscribeNow/`,
  share: `${url}/user/shareWithAudience`,
  uploadft: `${url}/nft/uploadNFT`,
  createNft: `${url}/nft/createNft`,
  nftList: `${url}/nft/nftList`,
  myNftList: `${url}/nft/myNftList`,
  addNft: `${url}/nft/nft`,
  viewNft: `${url}/nft/viewNft/`,
  order: `${url}/order/order`,
  sendOrderToUser: `${url}/sendOrderToUser/order`,
  staticContentList: `${url}/static/staticContentList`,
  viewStaticPage: `${url}/static/staticContent`,
  cancelOrder: `${url}/order/cancelOrder?_id=`,

  edit: `${url}/nft/nft`,
  del: `${url}/nft/nft`,
  placebid: `${url}/bid/bid`,
  getbid: `${url}/bid/bid`,
  myBid: `${url}/bid/myBid`,
  sublist: `${url}/user/subscriberList`,
  allorder: `${url}/order/allListOrder`,
  userlist: `${url}/user/userList`,
  orderwithid: `${url}/order/order/`,
  bids: `${url}/bid/bid/`,
  report: `${url}/user/reportNow/`,
  userlogin: `${url}/user/login`,
  register: `${url}/user/register`,
  forgotpass: `${url}/admin/forgotPassword`,
  reset: `${url}/admin/resetPassword/`,
  resetPassword: `${url}/admin/resetPassword/`,
  getbalance: `${url}/blockchain/getBalance/`,
  transfer: `${url}/blockchain/transfer`,
  // TODO: delete
  bnbTransfer: `${url}/blockchain/bnbTransfer`,
  // TODO: delete
  ethTransfer: `${url}/blockchain/ethTransfer`,
  btcTransfer: `${url}/blockchain/btcTransfer`,

  withdraw: `${url}/blockchain/withdraw`,
  sendOrderToUser: `${url}/order/sendOrderToUser`,
  soldOrderList: `${url}/order/soldOrderList`,
  buyOrderList: `${url}/order/buyOrderList`,
  auctionNftList: `${url}/order/auctionNftList`,
  auctionNft: `${url}/order/auctionNft/`,
  myAuctionNftList: `${url}/order/myAuctionNftList`,
  likeDislikeNft: `${url}/user/likeDislikeNft/`,
  donation: `${url}/user/donation`,
  listBid: `${url}/bid/listBid`,
  acceptBid: `${url}/bid/acceptBid`,
  chathistory: `${url}/socket/chathistory`,
  userAllDetails: `${url}/user/userAllDetails/`,
  getUser: `${url}/user/getUser/`,
  getCertificates: `${url}/user/getCertificates`,
  listAllNft: `${url}/nft/listAllNft`,
  followProfile: `${url}/user/followProfile/`,
  profileFollowersList: `${url}/user/profileFollowersList`,
  profileFollowingList: `${url}/user/profileFollowingList`,
  donateUserList: `${url}/user/donateUserList`,
  readChat: `${url}/socket/readChat/`,
  latestUserList: `${url}/user/latestUserList`,
  listFee: `${url}/admin/listFee`,
  lisasastFee: `${url}/admin/listFeeasas`, //formerge
  readNotification: `${url}/notification/readNotification`,
  likeDislikeUser: `${url}/user/likeDislikeUser/`,
  bundlePostList: `${url}/user/bundlePostList/`,
  bundleContentList: `${url}/user/bundleContentList`,
  getCoinBalance: `${url}/user/getCoinBalance`,
  allUserList: `${url}/user/allUserList`,
  exportNFT: `${url}/user/exportNFT`,
  totalEarnings: `${url}/user/totalEarnings`,
  // socail
  listSocial: `${url}/admin/listSocial`,
  getBanner: `${url}/user/getAdvertisement`,
  getBannerBackground: `${url}/user/getBanners`,
  getVideos: `${url}/user/getVideos`,
  content: `${url}/content/content`,
};

export default Apiconfigs;
